[project]
name = "mcp-server-weather"
version = "0.1.0"
description = "A Model Context Protocol (MCP) server that provides weather data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.18.0",
]
